version: "3.9"
services:
    cache:
        image: docker.io/redis
        volumes:
            - cache_data:/data
        healthcheck:
            test: "redis-cli ping"
            start_period: 5s
            interval: 1s
            timeout: 1s
    twitter-bot:
        image: twitter-collection-bot:latest
        build:
            context: .
            dockerfile: Containerfile
        depends_on:
            cache:
                condition: service_healthy
        environment:
            - REDIS_URL=redis://cache:6379
            - NODE_ENV=production
            - TWEET_RECORD_PATH=/data/record.json
            - TWEET_COLLECTION_PATH=/data/images/collection

            # Passed through from parent
            - AZURE_TRANSLATE_API_KEY
            - TWITTER_CONSUMER_KEY
            - TWITTER_CONSUMER_SECRET
            - TWITTER_ACCESS_TOKEN_KEY
            - TWITTER_ACCESS_TOKEN_SECRET
        volumes:
            - ./record.json:/data/record.json:ro
            - ./images:/data/images:ro
volumes:
    cache_data:

